### PR TITLE
Application Schema and CIL Schema separate flattened (V25)

### PR DESCRIPTION
**Pull request by aleksandr-suvorov**
AppSescriptor Schema V25 (1.24.0):
1. two separate schemas
2. removed extra http://adaptivecards.io reference

### CODE REVIEW

**Comment by silkearians** [comment]
Thanks a lot Alex. Please also mention that this is new V25 ...
Was there also a change in naming the definitions? Why?

**Comment by bd82** [comment]
I do not have an opinion on the split up of the schemas.
As long as the reference: `https://raw.githubusercontent.com/SAP/ui5-manifest/master/schema.json`
remains valid for the common scenario.

**Comment by aleksandr-suvorov** [comment]
@silkearians I moved both (app & cil) references out of "anyOf" array, and the links changed accordingly

**Comment by silkearians** [comment]
> @silkearians I moved both (app & cil) references out of "anyOf" array, and the links changed accordingly

Thanks Alex, I am only confused as the diff for schema.json shows many differences, or is it only a display issue?

**Comment by aleksandr-suvorov** [comment]
@silkearians definition which were previously located in subschemas, like sap.app, sap.ui5 and so on, are now located in the root of schema.

**Comment by silkearians** [comment]
Please also mention that this is new V25 ...

**Pull request merged**
